### PR TITLE
Upgraded AutoMapper to v5.1.1.

### PR DESCRIPTION
**Pull request by HawkMG**
Hi,

i have upgraded to the newest AutoMapper Version!

AutoMapper.Unity throws an Exception in Version 5.0.16 when I call RegisterMapper. With this upgrade everything works fine!

### CODE REVIEW

**Comment by srogovtsev** [comment]
@HawkMG, can you try new [6.0.0](https://www.nuget.org/packages/AutoMapper.Unity/6.0.0) version of AutoMapper.Unity and check whether you still have the exception?

**Comment by HawkMG** [comment]
Hi, I have tried the new Version 6.0.0. It works fine!

Are you planning to create another version with Automapper 5.1.1?

**Comment by srogovtsev** [comment]
Yes, most likely (I need it for PCL), but you should be able to use AutoMapper 5.1.1 with AutoMapper.Unity 6.0.0.

**Comment by HawkMG** [comment]
Ok, great to hear that :-)! Yes, I can use Automapper 5.1.1 with Automapper.Unity 6.0.0

**Pull request closed without merging**
